import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:url_launcher/url_launcher.dart';
import '../../models/request_model.dart';
import '../../services/request_service.dart';
import '../../theme/app_theme.dart';
import '../../widgets/claude_widgets.dart';
import '../../config.dart';
import 'add_request_screen.dart';
import '../Work_Orders/add_work_order.dart';
import '../../models/work_order.dart';
import '../../services/work_order_service.dart';

class RequestDetailScreen extends StatefulWidget {
  final RequestModel request;
  final String userRole;

  const RequestDetailScreen({
    super.key,
    required this.request,
    required this.userRole,
  });

  @override
  State<RequestDetailScreen> createState() => _RequestDetailScreenState();
}

class _RequestDetailScreenState extends State<RequestDetailScreen> {
  final _service = RequestService();
  final _woService = WorkOrderService();
  bool _loadingLinkedWo = true;
  List<Map<String, dynamic>> _attachments = [];
  String _deletingAttachmentId = '';
  WorkOrder? _linkedWorkOrder;

  String get _email =>
      Supabase.instance.client.auth.currentUser?.email ?? '';

  @override
  void initState() {
    super.initState();
    _loadAttachments();
    _loadLinkedWorkOrder();
  }

  Future<void> _loadLinkedWorkOrder() async {
    try {
      final results = await _woService.fetchWorkOrders(requestId: widget.request.id);
      if (!mounted) return;
      setState(() {
        _linkedWorkOrder = results.isNotEmpty ? results.first : null;
        _loadingLinkedWo = false;
      });
    } catch (_) {
      if (!mounted) return;
      setState(() => _loadingLinkedWo = false);
    }
  }

  Future<void> _openLinkedWorkOrder() async {
    if (_linkedWorkOrder == null) return;
    final result = await Navigator.push(
      context,
      MaterialPageRoute(
        builder: (_) => AddWorkOrderScreen(workOrder: _linkedWorkOrder!),
      ),
    );
    if (!mounted) return;
    if (result == 'deleted') {
      await _loadLinkedWorkOrder();
    }
  }

  Future<void> _loadAttachments() async {
    try {
      final list = await _service.fetchAttachments(widget.request.id);
      if (mounted) setState(() => _attachments = list);
    } catch (_) {}
  }

  Future<void> _deleteAttachment(String attachmentId) async {
    setState(() => _deletingAttachmentId = attachmentId);
    try {
      await _service.deleteAttachment(
        requestId: widget.request.id,
        attachmentId: attachmentId,
        email: _email,
      );
      if (mounted) {
        setState(() => _attachments.removeWhere((a) => a['id'] == attachmentId));
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Failed to delete: $e'),
            backgroundColor: AppColors.dangerText,
            behavior: SnackBarBehavior.floating,
          ),
        );
      }
    } finally {
      if (mounted) setState(() => _deletingAttachmentId = '');
    }
  }

  Future<void> _openAttachment(String filePath) async {
    // filePath is like /files/req_uuid.jpg — prepend the server base without /api
    final baseWithoutApi = AppConfig.baseUrl.replaceAll('/api', '');
    final url = Uri.parse('$baseWithoutApi$filePath');
    if (await canLaunchUrl(url)) {
      await launchUrl(url, mode: LaunchMode.externalApplication);
    }
  }

  bool get _canConvert =>
      (widget.userRole == 'tech' || widget.userRole == 'admin') &&
      widget.request.status == 'Open';

  bool get _canEdit =>
      widget.userRole == 'requester' && widget.request.status == 'Open';

  Future<void> _openEdit() async {
    final updated = await Navigator.push<bool>(
      context,
      MaterialPageRoute(
        builder: (_) => AddRequestScreen(request: widget.request),
      ),
    );
    if (updated == true && mounted) Navigator.pop(context, true);
  }

  Future<void> _convertToWorkOrder() async {
    final req = widget.request;
    final now = DateTime.now();
    final jobNo =
        'WO${now.year.toString().substring(2)}${now.month.toString().padLeft(2, '0')}${now.day.toString().padLeft(2, '0')}-'
        '${now.hour.toString().padLeft(2, '0')}${now.minute.toString().padLeft(2, '0')}${now.second.toString().padLeft(2, '0')}';

    final result = await Navigator.push(
      context,
      MaterialPageRoute(
        builder: (_) => AddWorkOrderScreen(
          autoGeneratedJobNo: jobNo,
          prefillTitle: req.title,
          prefillLocation: req.location,
          sourceRequestId: req.id,
        ),
      ),
    );

    if (!mounted) return;
    if (result is WorkOrder) {
      await Navigator.push(
        context,
        MaterialPageRoute(
          builder: (_) => AddWorkOrderScreen(workOrder: result),
        ),
      );
      if (!mounted) return;
      Navigator.pop(context, true);
    }
  }

  @override
  Widget build(BuildContext context) {
    final req = widget.request;
    final isOpen = req.status == 'Open';

    return Scaffold(
      backgroundColor: AppColors.bgPrimary,
      body: SafeArea(
        child: Column(
          children: [
            // ── Header ──────────────────────────────────────────
            Container(
              color: AppColors.bgSurface,
              padding: const EdgeInsets.fromLTRB(16, 12, 16, 12),
              child: Row(
                children: [
                  GestureDetector(
                    onTap: () => Navigator.pop(context),
                    child: Container(
                      width: 34,
                      height: 34,
                      decoration: BoxDecoration(
                        color: AppColors.bgSurface2,
                        borderRadius: BorderRadius.circular(9),
                        border: Border.all(
                            color: AppColors.border2, width: 0.5),
                      ),
                      child: Icon(Icons.arrow_back_rounded,
                          size: 16, color: AppColors.textSecondary),
                    ),
                  ),
                  SizedBox(width: 12),
                  Expanded(
                    child: Text(
                      'Request Detail',
                      style: TextStyle(
                        fontSize: 16,
                        fontWeight: FontWeight.w600,
                        color: AppColors.textPrimary,
                        letterSpacing: -0.3,
                      ),
                    ),
                  ),
                  if (_canEdit) ...[
                    GestureDetector(
                      onTap: _openEdit,
                      child: Container(
                        width: 34,
                        height: 34,
                        decoration: BoxDecoration(
                          color: AppColors.bgSurface2,
                          borderRadius: BorderRadius.circular(9),
                          border: Border.all(color: AppColors.border2, width: 0.5),
                        ),
                        child: Icon(Icons.edit_outlined,
                            size: 16, color: AppColors.textSecondary),
                      ),
                    ),
                    SizedBox(width: 8),
                  ],
                  _StatusPill(status: req.status),
                ],
              ),
            ),

            Divider(height: 0, thickness: 0.5, color: AppColors.border),

            // ── Content ─────────────────────────────────────────
            Expanded(
              child: SingleChildScrollView(
                padding: const EdgeInsets.all(16),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    // Title
                    SurfaceCard(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(
                            req.title,
                            style: TextStyle(
                              fontSize: 15,
                              fontWeight: FontWeight.w600,
                              color: AppColors.textPrimary,
                            ),
                          ),
                          if (req.description.isNotEmpty) ...[
                            SizedBox(height: 8),
                            Text(
                              req.description,
                              style: TextStyle(
                                fontSize: 13,
                                color: AppColors.textSecondary,
                                height: 1.5,
                              ),
                            ),
                          ],
                        ],
                      ),
                    ),

                    SizedBox(height: 12),

                    // Meta info
                    SectionLabel(text: 'Requester info'),
                    SurfaceCard(
                      padding: const EdgeInsets.symmetric(horizontal: 14),
                      child: Column(
                        children: [
                          _InfoRow(
                            icon: Icons.person_outline_rounded,
                            label: 'Name',
                            value: req.requesterName,
                          ),
                          if (req.location.isNotEmpty)
                            _InfoRow(
                              icon: Icons.location_on_outlined,
                              label: 'Location',
                              value: req.location,
                              showDivider: false,
                            )
                          else
                            _InfoRow(
                              icon: Icons.email_outlined,
                              label: 'Email',
                              value: req.createdBy,
                              showDivider: false,
                            ),
                        ],
                      ),
                    ),

                    SizedBox(height: 12),

                    SectionLabel(text: 'Timeline'),
                    SurfaceCard(
                      padding: const EdgeInsets.symmetric(horizontal: 14),
                      child: Column(
                        children: [
                          _InfoRow(
                            icon: Icons.calendar_today_outlined,
                            label: 'Submitted',
                            value: _formatDate(req.createdAt),
                            showDivider: !isOpen,
                          ),
                          if (!isOpen && req.closedAt != null) ...[
                            _InfoRow(
                              icon: Icons.check_circle_outline_rounded,
                              label: 'Closed',
                              value: _formatDate(req.closedAt!),
                              showDivider: req.closedBy != null,
                            ),
                            if (req.closedBy != null)
                              _InfoRow(
                                icon: Icons.engineering_outlined,
                                label: 'Closed by',
                                value: req.closedBy!.split('@').first,
                                showDivider: false,
                              ),
                          ],
                        ],
                      ),
                    ),

                    // Tech notes (if closed)
                    if (!isOpen && req.techNotes != null &&
                        req.techNotes!.isNotEmpty) ...[
                      SizedBox(height: 12),
                      SectionLabel(text: 'Tech notes'),
                      SurfaceCard(
                        child: Text(
                          req.techNotes!,
                          style: TextStyle(
                            fontSize: 13,
                            color: AppColors.textSecondary,
                            height: 1.5,
                          ),
                        ),
                      ),
                    ],

                    // Attachments
                    if (_attachments.isNotEmpty) ...[
                      SizedBox(height: 12),
                      SectionLabel(text: 'Attachments'),
                      SurfaceCard(
                        padding: const EdgeInsets.symmetric(vertical: 4),
                        child: Column(
                          children: [
                            for (int i = 0; i < _attachments.length; i++)
                              _AttachmentRow(
                                attachment: _attachments[i],
                                isDeleting: _deletingAttachmentId == _attachments[i]['id'],
                                canDelete: _attachments[i]['uploaded_by'] == _email,
                                onTap: () => _openAttachment(_attachments[i]['file_path'] as String),
                                onDelete: () => _deleteAttachment(_attachments[i]['id'] as String),
                              ),
                          ],
                        ),
                      ),
                    ],

                    // Convert to Work Order button (tech/admin only, open requests)
                    if (_canConvert && !_loadingLinkedWo) ...[
                      SizedBox(height: 24),
                      SizedBox(
                        width: double.infinity,
                        child: OutlinedButton.icon(
                          onPressed: _linkedWorkOrder != null
                              ? _openLinkedWorkOrder
                              : _convertToWorkOrder,
                          icon: Icon(
                            _linkedWorkOrder != null
                                ? Icons.open_in_new_rounded
                                : Icons.assignment_add,
                            size: 16,
                          ),
                          label: Text(
                            _linkedWorkOrder != null
                                ? 'Open Work Order'
                                : 'Convert to Work Order',
                            style: TextStyle(fontSize: 13, fontWeight: FontWeight.w600),
                          ),
                          style: OutlinedButton.styleFrom(
                            foregroundColor: AppColors.accent,
                            side: BorderSide(
                              color: AppColors.accent,
                              width: 0.5,
                            ),
                            padding: const EdgeInsets.symmetric(vertical: 14),
                            shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(10)),
                          ),
                        ),
                      ),
                    ],
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  String _formatDate(DateTime dt) =>
      '${dt.day}/${dt.month}/${dt.year}  ${dt.hour.toString().padLeft(2, '0')}:${dt.minute.toString().padLeft(2, '0')}';
}

// ── Widgets ───────────────────────────────────────────────────────────────────

class _StatusPill extends StatelessWidget {
  final String status;
  const _StatusPill({required this.status});

  @override
  Widget build(BuildContext context) {
    final isOpen = status == 'Open';
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
      decoration: BoxDecoration(
        color: isOpen ? AppColors.pendingBg : AppColors.closedBg,
        borderRadius: BorderRadius.circular(20),
      ),
      child: Text(
        status,
        style: TextStyle(
          fontSize: 11,
          fontWeight: FontWeight.w500,
          color: isOpen ? AppColors.pendingText : AppColors.closedText,
        ),
      ),
    );
  }
}

class _InfoRow extends StatelessWidget {
  final IconData icon;
  final String label;
  final String value;
  final bool showDivider;

  const _InfoRow({
    required this.icon,
    required this.label,
    required this.value,
    this.showDivider = true,
  });

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Padding(
          padding: const EdgeInsets.symmetric(vertical: 11),
          child: Row(
            children: [
              Container(
                width: 32,
                height: 32,
                decoration: BoxDecoration(
                  color: AppColors.bgSurface2,
                  borderRadius: BorderRadius.circular(8),
                ),
                child: Icon(icon, size: 15, color: AppColors.textSecondary),
              ),
              SizedBox(width: 12),
              Expanded(
                child: Text(
                  label,
                  style: TextStyle(
                    fontSize: 13,
                    fontWeight: FontWeight.w500,
                    color: AppColors.textPrimary,
                  ),
                ),
              ),
              Text(
                value,
                style: TextStyle(
                  fontSize: 12,
                  color: AppColors.textSecondary,
                ),
              ),
            ],
          ),
        ),
        if (showDivider)
          Divider(height: 0, thickness: 0.5, color: AppColors.border),
      ],
    );
  }
}

class _AttachmentRow extends StatelessWidget {
  final Map<String, dynamic> attachment;
  final bool isDeleting;
  final bool canDelete;
  final VoidCallback onTap;
  final VoidCallback onDelete;

  const _AttachmentRow({
    required this.attachment,
    required this.isDeleting,
    required this.canDelete,
    required this.onTap,
    required this.onDelete,
  });

  bool get _isImage {
    final ext = (attachment['file_name'] as String? ?? '').split('.').last.toLowerCase();
    return ['jpg', 'jpeg', 'png', 'gif', 'webp', 'bmp'].contains(ext);
  }

  @override
  Widget build(BuildContext context) {
    final fileName = attachment['file_name'] as String? ?? 'file';
    return InkWell(
      onTap: onTap,
      child: Padding(
        padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 10),
        child: Row(
          children: [
            Container(
              width: 32,
              height: 32,
              decoration: BoxDecoration(
                color: AppColors.bgSurface2,
                borderRadius: BorderRadius.circular(8),
              ),
              child: Icon(
                _isImage ? Icons.image_outlined : Icons.insert_drive_file_outlined,
                size: 15,
                color: AppColors.textSecondary,
              ),
            ),
            SizedBox(width: 10),
            Expanded(
              child: Text(
                fileName,
                style: TextStyle(
                  fontSize: 12,
                  color: AppColors.textPrimary,
                  decoration: TextDecoration.underline,
                  decorationColor: AppColors.textTertiary,
                ),
                overflow: TextOverflow.ellipsis,
              ),
            ),
            if (canDelete)
              isDeleting
                  ? SizedBox(
                      width: 14,
                      height: 14,
                      child: CircularProgressIndicator(
                        strokeWidth: 1.5,
                        color: AppColors.textTertiary,
                      ),
                    )
                  : GestureDetector(
                      onTap: onDelete,
                      child: Icon(
                        Icons.delete_outline_rounded,
                        size: 16,
                        color: AppColors.textTertiary,
                      ),
                    ),
          ],
        ),
      ),
    );
  }
}
