name: work_order
description: "A new Flutter project."
publish_to: 'none'

version: 1.11.0+91

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.6
  cupertino_icons: ^1.0.8
  file_picker: ^10.3.10
  image_picker: ^1.1.2
  dio: ^5.4.0
  http: ^1.2.1
  syncfusion_flutter_pdfviewer: ^32.2.7
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  package_info_plus: ^8.0.0
  pdf: ^3.11.1
  htmltopdfwidgets: ^2.0.1
  printing: ^5.12.0
  url_launcher: ^6.2.5
  share_plus: ^10.0.0
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1
  web: ^1.1.1
  collection: ^1.18.0
  shimmer: ^3.0.0
  animations: ^2.0.8
  fl_chart: ^0.65.0
  connectivity_plus: ^5.0.2
  sqflite: ^2.3.0
  flutter_slidable: ^3.0.0
  table_calendar: ^3.1.2
  flutter_dotenv: ^6.0.0
  signature: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Calibri
      fonts:
        - asset: assets/fonts/calibri.ttf
        - asset: assets/fonts/calibrib.ttf
          weight: 700

  assets:
    - .env
    - assets/images/
    - assets/report_preview_burgundy.html
    - assets/work_order_system_intro.html
    - assets/fonts/calibri.ttf
    - assets/fonts/calibrib.ttf
    - assets/templates/payment_certificate.html
