import 'package:flutter/material.dart';
import '../models/work_order.dart';
import '../services/work_order_service.dart';

class AddWorkOrderScreen extends StatefulWidget {
  final WorkOrder? workOrder;
  final String? autoGeneratedJobNo;

  const AddWorkOrderScreen({
    super.key,
    this.workOrder,
    this.autoGeneratedJobNo,
  });

  @override
  State<AddWorkOrderScreen> createState() => _AddWorkOrderScreenState();
}

class _AddWorkOrderScreenState extends State<AddWorkOrderScreen> {
  final WorkOrderService _service = WorkOrderService();
  final _formKey = GlobalKey<FormState>();

  final TextEditingController jobNoController = TextEditingController();
  final TextEditingController clientController = TextEditingController();
  final TextEditingController descriptionController = TextEditingController();
  final TextEditingController locationController = TextEditingController();

  String selectedStatus = "Open";
  String selectedType = "Technical";

  @override
  void initState() {
    super.initState();

    if (widget.workOrder != null) {
      // EDIT MODE
      jobNoController.text = widget.workOrder!.jobNo;
      clientController.text = widget.workOrder!.client;
      descriptionController.text = widget.workOrder!.description;
      locationController.text = widget.workOrder!.location;

      selectedStatus = widget.workOrder!.status;
      selectedType = widget.workOrder!.type;
    } else {
      // ADD MODE
      jobNoController.text = widget.autoGeneratedJobNo ?? "";
    }
  }

  Future<void> submit() async {
    if (_formKey.currentState!.validate()) {
      final now = DateTime.now().toString();

      final newWorkOrder = WorkOrder(
        id: widget.workOrder?.id ?? '',
        jobNo: jobNoController.text,
        client: clientController.text,
        status: selectedStatus,
        description: descriptionController.text,
        location: locationController.text,
        type: selectedType,
        dateCreated: widget.workOrder?.dateCreated ?? now,
        dateModified: now,
      );

      if (widget.workOrder == null) {
        // ADD
        await _service.addWorkOrder(newWorkOrder);
      } else {
        // UPDATE
        await _service.updateWorkOrder(newWorkOrder);
      }

      Navigator.pop(context); // no need to return object anymore
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(
          widget.workOrder == null ? "New Work Order" : "Edit Work Order",
        ),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16),
        child: Form(
          key: _formKey,
          child: SingleChildScrollView(
            child: Column(
              children: [
                TextFormField(
                  controller: jobNoController,
                  enabled: widget.workOrder == null,
                  decoration: const InputDecoration(labelText: "Job No"),
                  validator: (value) => value!.isEmpty ? "Enter Job No" : null,
                ),
                const SizedBox(height: 10),
                TextFormField(
                  controller: clientController,
                  decoration: const InputDecoration(labelText: "Client"),
                  validator: (value) => value!.isEmpty ? "Enter Client" : null,
                ),
                const SizedBox(height: 10),
                DropdownButtonFormField<String>(
                  initialValue: selectedStatus,
                  items: const [
                    DropdownMenuItem(value: "Open", child: Text("Open")),
                    DropdownMenuItem(
                      value: "In Progress",
                      child: Text("In Progress"),
                    ),
                    DropdownMenuItem(value: "Closed", child: Text("Closed")),
                  ],
                  onChanged: (value) {
                    setState(() {
                      selectedStatus = value!;
                    });
                  },
                  decoration: const InputDecoration(labelText: "Status"),
                ),
                const SizedBox(height: 10),
                TextFormField(
                  controller: locationController,
                  decoration: const InputDecoration(labelText: "Location"),
                  validator: (value) =>
                      value!.isEmpty ? "Enter Location" : null,
                ),
                const SizedBox(height: 10),
                DropdownButtonFormField<String>(
                  initialValue: selectedType,
                  items: const [
                    DropdownMenuItem(
                      value: "Technical",
                      child: Text("Technical"),
                    ),
                    DropdownMenuItem(value: "Other", child: Text("Other")),
                  ],
                  onChanged: (value) {
                    setState(() {
                      selectedType = value!;
                    });
                  },
                  decoration: const InputDecoration(labelText: "Type"),
                ),
                const SizedBox(height: 10),
                TextFormField(
                  controller: descriptionController,
                  decoration: const InputDecoration(labelText: "Description"),
                  maxLines: 3,
                ),
                const SizedBox(height: 20),
                ElevatedButton(
                  onPressed: submit,
                  child: Text(
                    widget.workOrder == null
                        ? "Add Work Order"
                        : "Save Changes",
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
