import 'package:flutter/material.dart';
import '../models/work_order.dart';
import '../widgets/work_order_card.dart';
import '../services/work_order_service.dart';

import 'add_work_order.dart';

class WorkOrderHome extends StatefulWidget {
  const WorkOrderHome({super.key});

  @override
  State<WorkOrderHome> createState() => _WorkOrderHomeState();
}

class _WorkOrderHomeState extends State<WorkOrderHome> {
  String selectedFilter = "All";
  int? expandedIndex;
  final WorkOrderService _service = WorkOrderService();
  List<WorkOrder> workOrders = [];

  @override
  void initState() {
    super.initState();
    loadWorkOrders();
  }

  Future<void> loadWorkOrders() async {
    final data = await _service.fetchWorkOrders();
    setState(() {
      workOrders = data;
    });
  }

  Future<void> openAddScreen() async {
    final nextNumber = workOrders.length + 1001;
    final autoJobNo = "WO-$nextNumber";

    await Navigator.push(
      context,
      MaterialPageRoute(
        builder: (_) => AddWorkOrderScreen(
          autoGeneratedJobNo: autoJobNo,
        ),
      ),
    );

    await loadWorkOrders(); // ✅ ALWAYS reload after returning
  }

  @override
  Widget build(BuildContext context) {
    List<WorkOrder> filteredOrders = selectedFilter == "All"
        ? workOrders
        : workOrders.where((wo) => wo.status == selectedFilter).toList();

    return Scaffold(
      backgroundColor: Theme.of(context).colorScheme.surface,
      appBar: AppBar(
        title: const Text("Work Orders"),
        centerTitle: true,
        backgroundColor: Color.fromARGB(237, 221, 226, 226),
        foregroundColor: Colors.black,
        elevation: 0,
        actions: [
          IconButton(
            icon: const Icon(Icons.add),
            onPressed: openAddScreen,
          ),
          IconButton(
            icon: const Icon(Icons.search),
            onPressed: () {},
          ),
        ],
      ),
      body: Column(
        children: [
          const SizedBox(height: 10),

          // ✅ FILTER BUTTONS
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 16),
            child: Container(
              decoration: BoxDecoration(
                color: Theme.of(context).colorScheme.surfaceContainerHighest,
                borderRadius: BorderRadius.circular(30),
              ),
              child: Row(
                children: [
                  buildFilterButton("All"),
                  buildFilterButton("Pending"),
                  buildFilterButton("In Progress"),
                  buildFilterButton("Closed"),
                ],
              ),
            ),
          ),

          const SizedBox(height: 10),

          // ✅ LIST
          // ✅ LIST (SMOOTH ANIMATED VERSION)
          Expanded(
            child: RefreshIndicator(
              onRefresh: loadWorkOrders,
              child: AnimatedSwitcher(
                duration: const Duration(milliseconds: 350),
                switchInCurve: Curves.easeInOut,
                switchOutCurve: Curves.easeInOut,
                transitionBuilder: (child, animation) {
                  return FadeTransition(
                    opacity: animation,
                    child: SlideTransition(
                      position: Tween<Offset>(
                        begin: const Offset(0.05, 0),
                        end: Offset.zero,
                      ).animate(animation),
                      child: child,
                    ),
                  );
                },
                child: filteredOrders.isEmpty
                    ? ListView(
                        key: const ValueKey("empty"),
                        physics: const AlwaysScrollableScrollPhysics(),
                        children: const [
                          SizedBox(height: 150),
                          Center(child: Text("No Work Orders")),
                        ],
                      )
                    : ListView.builder(
                        key: ValueKey(selectedFilter), // 🔥 important
                        physics: const AlwaysScrollableScrollPhysics(),
                        padding: const EdgeInsets.all(16),
                        itemCount: filteredOrders.length,
                        itemBuilder: (context, index) {
                          final workOrder = filteredOrders[index];

                          return WorkOrderCard(
                            workOrder: workOrder,
                            onTap: () {
                              setState(() {
                                expandedIndex =
                                    expandedIndex == index ? null : index;
                              });
                            },
                            isExpanded: expandedIndex == index,
                            onEdit: () async {
                              await Navigator.push(
                                context,
                                MaterialPageRoute(
                                  builder: (_) =>
                                      AddWorkOrderScreen(workOrder: workOrder),
                                ),
                              );

                              await loadWorkOrders();
                            },
                          );
                        },
                      ),
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget buildFilterButton(String status) {
    final theme = Theme.of(context);
    final isSelected = selectedFilter == status;

    return Expanded(
      child: GestureDetector(
        onTap: () {
          setState(() {
            selectedFilter = status;
            expandedIndex = null; // prevents animation glitch
          });
          ;
        },
        child: AnimatedContainer(
          duration: const Duration(milliseconds: 250),
          curve: Curves.easeOut,
          padding: const EdgeInsets.symmetric(vertical: 12),
          decoration: BoxDecoration(
            color: isSelected ? theme.colorScheme.primary : Colors.transparent,
            borderRadius: BorderRadius.circular(30),
          ),
          child: Center(
            child: Text(
              status,
              style: TextStyle(
                color: isSelected
                    ? theme.colorScheme.onPrimary
                    : theme.colorScheme.onSurface,
                fontWeight: FontWeight.w600,
              ),
            ),
          ),
        ),
      ),
    );
  }
}
