import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:http/http.dart' as http;
import 'package:file_picker/file_picker.dart';
import 'dart:convert';
import '../../models/work_order.dart';
import '../../models/work_order_comment.dart';
import '../../models/work_order_attachment.dart';
import '../../services/work_order_service.dart';
import '../../models/user.dart';
import '../../services/user_service.dart';
import '../../services/department_service.dart';
import '../../models/department.dart';
import '../../models/technician_assignment.dart';
import '../../widgets/technician_selector.dart';
import '../../widgets/attachment_widget.dart';
import '../../theme/app_theme.dart';
import '../../config.dart';

class AddWorkOrderScreen extends StatefulWidget {
  final WorkOrder? workOrder;
  final String? autoGeneratedJobNo;
  final String? prefillTitle;
  final String? prefillLocation;
  final String? sourceRequestId;
  final int initialTab;
  final String userRole;

  const AddWorkOrderScreen({
    super.key,
    this.workOrder,
    this.autoGeneratedJobNo,
    this.prefillTitle,
    this.prefillLocation,
    this.sourceRequestId,
    this.initialTab = 0,
    this.userRole = 'admin',
  });

  @override
  State<AddWorkOrderScreen> createState() => _AddWorkOrderScreenState();
}

class _AddWorkOrderScreenState extends State<AddWorkOrderScreen> {
  final UserService _userService = UserService();
  final DepartmentService _departmentService = DepartmentService();
  final WorkOrderService _service = WorkOrderService();
  final _formKey = GlobalKey<FormState>();

  final _titleFocusNode = FocusNode();
  final _descriptionFocusNode = FocusNode();
  final _locationFocusNode = FocusNode();
  final _mobileFocusNode = FocusNode();

  List<AppUser> _employees = [];
  List<String> _selectedEmployeeIds = [];

  final TextEditingController jobNoController = TextEditingController();
  final TextEditingController clientController = TextEditingController();
  final TextEditingController descriptionController = TextEditingController();
  final TextEditingController locationController = TextEditingController();
  final TextEditingController mobileController = TextEditingController();
  String selectedDepartment = "General";
  String selectedDepartmentId = '';

  String selectedStatus = "Pending";
  String selectedType = "Technical";
  List<Department> _departments = [];

  // Activity tab state
  int _tabIndex = 0;
  List<WorkOrderComment> _comments = [];
  List<WorkOrderAttachment> _attachments = [];
  bool _commentsLoading = false;
  bool _refreshing = false;
  bool _sending = false;
  bool _roleLoaded = false;
  String _userRole = 'admin';
  bool _isTechnician = false;
  final TextEditingController _commentCtrl = TextEditingController();
  final ScrollController _activityScrollCtrl = ScrollController();
  PlatformFile? _pendingAttachment;

  static const List<String> _allowedTypes = [
    "Technical",
    "Inspection",
    "Other",
  ];

  static const List<String> _allowedStatuses = [
    "Pending",
    "In Progress",
    "Closed",
  ];

  bool get _isRequester => _roleLoaded && _userRole == 'requester';
  bool get _isReporter => _roleLoaded && _userRole == 'reporter';

  @override
  void initState() {
    super.initState();
    _loadUserRole();
    _loadDepartments();
    if (widget.workOrder != null) {
      jobNoController.text = widget.workOrder!.jobNo;
      clientController.text = widget.workOrder!.title;
      descriptionController.text = widget.workOrder!.description;
      locationController.text = widget.workOrder!.location;
      mobileController.text = widget.workOrder!.mobileNumber ?? '';
      selectedDepartment = widget.workOrder!.department;
      selectedDepartmentId = widget.workOrder!.departmentId;
      selectedStatus = _allowedStatuses.contains(widget.workOrder!.status)
          ? widget.workOrder!.status
          : "Pending";
      selectedType = _allowedTypes.contains(widget.workOrder!.type)
          ? widget.workOrder!.type
          : "Technical";
      _tabIndex = widget.initialTab;
      _loadComments();
    } else {
      jobNoController.text = widget.autoGeneratedJobNo ?? "";
      if (widget.prefillTitle != null) clientController.text = widget.prefillTitle!;
      if (widget.prefillLocation != null) locationController.text = widget.prefillLocation!;
      selectedDepartment = 'General';
      mobileController.text = '';
    }
  }

Future<void> _loadDepartments() async {
  try {
    final departments = await _departmentService.fetchDepartments(isActive: true);
    if (mounted) {
      setState(() {
        _departments = departments..sort((a, b) => a.name.compareTo(b.name));
        // Sync selectedDepartmentId from name match or default to first
        final match = _departments.where((d) => d.name == selectedDepartment).firstOrNull;
        if (match != null) {
          selectedDepartmentId = match.id;
        } else if (_departments.isNotEmpty && selectedDepartmentId.isEmpty) {
          selectedDepartment = _departments.first.name;
          selectedDepartmentId = _departments.first.id;
        }
      });
      // Load employees filtered by resolved department (technicians will reload in _loadUserRole)
      _loadEmployees();
    }
  } catch (_) {}
}

  Future<void> _loadUserRole() async {
    try {
      final email = Supabase.instance.client.auth.currentUser?.email ?? '';
      if (email.isEmpty) {
        if (mounted) {
          setState(() {
            _roleLoaded = true;
            _userRole = 'admin';
          });
        }
        return;
      }
      final res = await http.get(
        Uri.parse('${AppConfig.baseUrl}/user-role?email=${Uri.encodeComponent(email)}'),
      );
      if (res.statusCode == 200) {
        final data = jsonDecode(res.body);
        final role = data['user_type'] ?? 'admin';
        if (!mounted) return;
        setState(() {
          _roleLoaded = true;
          _userRole = role;
        });
        if (role == 'requester') {
          _loadUserProfile(email);
        } else if (role == 'technician') {
          _isTechnician = true;
          final currentUser = await _userService.fetchCurrentUser();
          if (currentUser != null && currentUser.technicianDepartments.isNotEmpty) {
            final dept = currentUser.technicianDepartments.first;
            if (mounted) {
              setState(() {
                selectedDepartmentId = dept['id']!;
                selectedDepartment = dept['name']!;
              });
              _loadEmployees(departmentId: dept['id']);
            }
          }
        }
      } else {
        if (!mounted) return;
        setState(() {
          _roleLoaded = true;
          _userRole = 'admin';
        });
      }
    } catch (_) {
      if (!mounted) return;
      setState(() {
        _roleLoaded = true;
        _userRole = 'admin';
      });
    }
  }

  Future<void> _loadUserProfile(String email) async {
    if (email.isEmpty) return;
    try {
      final res = await http.get(
        Uri.parse('${AppConfig.baseUrl}/users/me?email=${Uri.encodeComponent(email)}'),
      );
      if (res.statusCode == 200 && mounted) {
        final data = jsonDecode(res.body);
        final user = data['user'];
        if (user != null) {
          setState(() {
            mobileController.text = (user['mobile'] ?? '').toString();
          });
        }
      }
    } catch (_) {}
  }

  @override
  void dispose() {
    _titleFocusNode.dispose();
    _descriptionFocusNode.dispose();
    _locationFocusNode.dispose();
    _mobileFocusNode.dispose();
    jobNoController.dispose();
    clientController.dispose();
    descriptionController.dispose();
    locationController.dispose();
    mobileController.dispose();
    _commentCtrl.dispose();
    _activityScrollCtrl.dispose();
    super.dispose();
  }

  Future<void> _loadEmployees({String? departmentId}) async {
    final deptId = departmentId ?? (selectedDepartmentId.isNotEmpty ? selectedDepartmentId : null);
    final data = await _userService.fetchTechnicians(departmentId: deptId);
    if (!mounted) return;
    setState(() {
      _employees = data;
      if (widget.workOrder != null) {
        _selectedEmployeeIds =
            widget.workOrder!.assignedTechnicians.map((t) => t.id).toList();
      }
    });
  }

  Future<void> _loadComments() async {
    if (widget.workOrder == null) return;
    if (!_refreshing) {
      setState(() => _commentsLoading = true);
    }
    try {
      final comments = await _service.fetchComments(widget.workOrder!.id);
      final attachments = await _service.fetchAttachments(widget.workOrder!.id);
      if (mounted) {
        setState(() {
          _comments = comments;
          _attachments = attachments;
        });
        WidgetsBinding.instance.addPostFrameCallback((_) {
          if (_activityScrollCtrl.hasClients) {
            _activityScrollCtrl.animateTo(
              _activityScrollCtrl.position.maxScrollExtent,
              duration: const Duration(milliseconds: 300),
              curve: Curves.easeOut,
            );
          }
        });
      }
    } catch (_) {}
    if (mounted) {
      setState(() {
        _commentsLoading = false;
        _refreshing = false;
      });
    }
  }

  Future<void> _pickAttachment() async {
    final file = await _service.pickAttachment();
    if (file != null && mounted) {
      setState(() => _pendingAttachment = file);
    }
  }

  void _removePendingAttachment() {
    setState(() => _pendingAttachment = null);
  }

  Future<void> _deleteAttachment(WorkOrderAttachment attachment) async {
    final success = await _service.deleteAttachment(
      widget.workOrder!.id,
      attachment.id,
    );
    if (success && mounted) {
      setState(() {
        _attachments.removeWhere((a) => a.id == attachment.id);
      });
    }
  }

  Future<void> _sendComment() async {
    final text = _commentCtrl.text.trim();
    final hasAttachment = _pendingAttachment != null;
    if (text.isEmpty && !hasAttachment) return;
    if (_sending) return;

    final email = Supabase.instance.client.auth.currentUser?.email ?? '';
    final name = email.split('@').first;

    setState(() => _sending = true);
    try {
      if (_pendingAttachment != null) {
        final attachment = await _service.uploadAttachment(
          workOrderId: widget.workOrder!.id,
          file: _pendingAttachment!,
        );
        if (attachment != null && mounted) {
          setState(() {
            _attachments = [..._attachments, attachment];
          });
        }
      }

      if (text.isNotEmpty) {
        final comment = await _service.addComment(
          workOrderId: widget.workOrder!.id,
          authorEmail: email,
          authorName: name,
          body: text,
        );
        if (comment != null && mounted) {
          _commentCtrl.clear();
          setState(() => _comments = [..._comments, comment]);
          WidgetsBinding.instance.addPostFrameCallback((_) {
            if (_activityScrollCtrl.hasClients) {
              _activityScrollCtrl.animateTo(
                _activityScrollCtrl.position.maxScrollExtent,
                duration: const Duration(milliseconds: 300),
                curve: Curves.easeOut,
              );
            }
          });
        }
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(
          content: Text('Failed to send: $e'),
          backgroundColor: AppColors.dangerText,
          behavior: SnackBarBehavior.floating,
        ));
      }
    }
    if (mounted) {
      setState(() {
        _sending = false;
        _pendingAttachment = null;
      });
    }
  }

  Future<void> submit() async {
    // Requesters can CREATE new work orders but cannot EDIT existing ones
    final isNewWorkOrder = widget.workOrder == null;
    if (_isRequester && !isNewWorkOrder) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Requester cannot edit work orders'),
          backgroundColor: AppColors.dangerText,
          behavior: SnackBarBehavior.floating,
        ),
      );
      return;
    }
    if (!_formKey.currentState!.validate()) return;
    if (selectedDepartmentId.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(
        content: Text('Please select a department'),
        backgroundColor: Colors.orange,
        behavior: SnackBarBehavior.floating,
      ));
      return;
    }
    try {
      final now = DateTime.now().toUtc().toIso8601String();
      final newWorkOrder = WorkOrder(
        id: widget.workOrder?.id ?? '',
        jobNo: jobNoController.text.trim(),
        title: clientController.text.trim(),
        status: selectedStatus,
        description: descriptionController.text.trim(),
        location: locationController.text.trim(),
        mobileNumber: mobileController.text.trim(),
        departmentName: selectedDepartment,
        departmentId: selectedDepartmentId,
        type: selectedType,
        dateCreated: widget.workOrder?.dateCreated ?? now,
        dateModified: now,
        assignedTechnicians: _selectedEmployeeIds
            .map((id) => TechnicianAssignment(id: id, fullName: ''))
            .toList(),
      );

      if (widget.workOrder == null) {
        try {
          final createdOrder = await _service.addWorkOrder(newWorkOrder);
          if (!mounted) return;
          Navigator.pop(context, createdOrder);
        } catch (e) {
          if (!mounted) return;
          ScaffoldMessenger.of(context).showSnackBar(SnackBar(
            content: Text('Failed to create work order: $e'),
            backgroundColor: AppColors.dangerText,
            behavior: SnackBarBehavior.floating,
            duration: Duration(seconds: 5),
          ));
          return;
        }
      } else {
        try {
          await _service.updateWorkOrder(newWorkOrder);
          if (!mounted) return;
          Navigator.pop(context, "updated");
        } catch (e) {
          if (!mounted) return;
          ScaffoldMessenger.of(context).showSnackBar(SnackBar(
            content: Text('Failed to update work order: $e'),
            backgroundColor: AppColors.dangerText,
            behavior: SnackBarBehavior.floating,
            duration: Duration(seconds: 5),
          ));
        }
      }
    } catch (e) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(SnackBar(
        content: Text('Error: $e'),
        backgroundColor: AppColors.dangerText,
        behavior: SnackBarBehavior.floating,
        duration: Duration(seconds: 5),
      ));
    }
  }

  IconData _typeIcon(String type) {
    switch (type) {
      case 'Inspection':
        return Icons.checklist_rounded;
      case 'Technical':
        return Icons.build_outlined;
      default:
        return Icons.work_outline_rounded;
    }
  }

  Color _typeColor(String type) {
    switch (type) {
      case 'Inspection':
        return AppColors.inProgressText;
      case 'Technical':
        return AppColors.accent;
      default:
        return AppColors.textSecondary;
    }
  }

  @override
  Widget build(BuildContext context) {
    final isEditing = widget.workOrder != null;

    return Scaffold(
      backgroundColor: AppColors.bgPrimary,
      resizeToAvoidBottomInset: true,
      bottomNavigationBar:
          (isEditing && _tabIndex == 1) ? _buildComposeBar() : null,
      body: SafeArea(
        child: Column(
          children: [
            // ── Header ────────────────────────────────────────────
            Container(
              color: AppColors.bgSurface,
              padding: const EdgeInsets.fromLTRB(16, 12, 16, 0),
              child: Column(
                children: [
                  Row(
                    children: [
                      GestureDetector(
                        onTap: () => Navigator.pop(context),
                        child: Container(
                          width: 34,
                          height: 34,
                          decoration: BoxDecoration(
                            color: AppColors.bgSurface2,
                            borderRadius: BorderRadius.circular(9),
                            border: Border.all(
                                color: AppColors.border2, width: 0.5),
                          ),
                          child: Icon(Icons.arrow_back_rounded,
                              size: 16, color: AppColors.textSecondary),
                        ),
                      ),
                      SizedBox(width: 12),
                      Expanded(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(
                              isEditing
                                  ? widget.workOrder!.title
                                  : 'New Work Order',
                              style: TextStyle(
                                fontSize: 16,
                                fontWeight: FontWeight.w600,
                                color: AppColors.textPrimary,
                                letterSpacing: -0.3,
                              ),
                              maxLines: 1,
                              overflow: TextOverflow.ellipsis,
                            ),
                            if (isEditing) ...[
                              SizedBox(height: 1),
                              Text(
                                widget.workOrder!.jobNo,
                                style: TextStyle(
                                    fontSize: 11,
                                    color: AppColors.textTertiary),
                              ),
                            ],
                          ],
                        ),
                      ),
                      if (isEditing)
                        _StatusPill(status: widget.workOrder!.status),
                    ],
                  ),

                  // Tabs (edit mode only)
                  if (isEditing) ...[
                    SizedBox(height: 10),
                    Row(
                      children: [
                        _Tab(
                          label: 'Details',
                          active: _tabIndex == 0,
                          onTap: () => setState(() => _tabIndex = 0),
                        ),
                        _Tab(
                          label: 'Activity',
                          active: _tabIndex == 1,
                          badge: _comments
                              .where((c) => c.type == 'comment')
                              .length,
                          onTap: () => setState(() => _tabIndex = 1),
                        ),
                      ],
                    ),
                  ] else
                    SizedBox(height: 12),
                ],
              ),
            ),

            Divider(height: 0, thickness: 0.5, color: AppColors.border),

            // ── Body ──────────────────────────────────────────────
            Expanded(
              child: isEditing && _tabIndex == 1
                  ? _buildActivityTab()
                  : _buildDetailsTab(),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildDetailsTab() {
    if (!_roleLoaded) {
      return const Center(child: CircularProgressIndicator());
    }
    // Requesters can CREATE new work orders, but cannot EDIT existing ones
    final isNewWorkOrder = widget.workOrder == null;
    final canEdit = !_isRequester || isNewWorkOrder;
    return SingleChildScrollView(
      padding: const EdgeInsets.all(16),
      child: Form(
        key: _formKey,
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            TextFormField(
              controller: jobNoController,
              readOnly: true,
              decoration: InputDecoration(
                labelText: "Job No",
                hintText: "Auto-generated",
                filled: true,
              ),
            ),
            if (widget.workOrder != null && (widget.workOrder!.createdByName != null || widget.workOrder!.createdByEmail != null)) ...[
              SizedBox(height: 10),
              TextFormField(
                initialValue: widget.workOrder!.createdByName ?? widget.workOrder!.createdByEmail,
                readOnly: true,
                decoration: InputDecoration(
                  labelText: "Created By",
                  filled: true,
                ),
              ),
            ],
            SizedBox(height: 10),
            TextFormField(
              controller: clientController,
              focusNode: _titleFocusNode,
              readOnly: !canEdit,
              decoration: InputDecoration(labelText: "Title"),
              textInputAction: TextInputAction.next,
              onFieldSubmitted: (_) {
                FocusScope.of(context).requestFocus(_descriptionFocusNode);
              },
              validator: (v) => v!.isEmpty ? "Enter Title" : null,
            ),
            SizedBox(height: 10),
            if (!_isReporter) ...[
              DropdownButtonFormField<String>(
                initialValue: selectedStatus,
                items: _allowedStatuses
                    .map((s) => DropdownMenuItem(value: s, child: Text(s)))
                    .toList(),
                onChanged: canEdit ? (v) => setState(() => selectedStatus = v!) : null,
                decoration: InputDecoration(labelText: "Status"),
              ),
              SizedBox(height: 10),
            ],
            TextFormField(
              controller: locationController,
              focusNode: _locationFocusNode,
              readOnly: !canEdit,
              decoration: InputDecoration(labelText: "Location"),
              textInputAction: TextInputAction.next,
              onFieldSubmitted: (_) {
                FocusScope.of(context).requestFocus(_mobileFocusNode);
              },
              validator: (v) => v!.isEmpty ? "Enter Location" : null,
            ),
            SizedBox(height: 10),
            TextFormField(
              controller: mobileController,
              readOnly: !canEdit,
              decoration: InputDecoration(labelText: "Mobile Number"),
              keyboardType: TextInputType.phone,
              textInputAction: TextInputAction.next,
            ),
            SizedBox(height: 10),
            DropdownButtonFormField<String>(
              initialValue: _departments.isEmpty ? 'General' : selectedDepartment,
              items: _departments.isEmpty
                  ? [DropdownMenuItem(value: 'General', child: Text('General'))]
                  : _departments.map((d) => DropdownMenuItem(value: d.name, child: Text(d.name))).toList(),
              onChanged: (canEdit && !_isTechnician) ? (v) {
                if (v != null) {
                  final dept = _departments.firstWhere((d) => d.name == v, orElse: () => _departments.first);
                  setState(() {
                    selectedDepartment = dept.name;
                    selectedDepartmentId = dept.id;
                  });
                  _loadEmployees(departmentId: dept.id);
                }
              } : null,
              decoration: InputDecoration(labelText: "Department"),
            ),
            SizedBox(height: 10),

            // ── Type dropdown with icons ───────────────────────────
            if (!_isReporter) ...[
              DropdownButtonFormField<String>(
                initialValue: selectedType,
                items: _allowedTypes.map((type) {
                  return DropdownMenuItem(
                    value: type,
                    child: Row(
                      children: [
                        Icon(_typeIcon(type),
                            size: 16, color: _typeColor(type)),
                        SizedBox(width: 8),
                        Text(type),
                      ],
                    ),
                  );
                }).toList(),
                onChanged: canEdit ? (v) => setState(() => selectedType = v!) : null,
                decoration: InputDecoration(labelText: "Type"),
              ),
              SizedBox(height: 10),
            ],

            TextFormField(
              controller: descriptionController,
              focusNode: _descriptionFocusNode,
              readOnly: !canEdit,
              decoration: InputDecoration(labelText: "Description"),
              maxLines: 3,
              textInputAction: TextInputAction.done,
            ),
            SizedBox(height: 25),
            // Only show Assign Employees for admin/tech (not for requesters)
            if (!_isRequester && !_isReporter) ...[
              Text(
                "Assign Technician",
                style:
                    TextStyle(fontSize: 16, fontWeight: FontWeight.w600),
              ),
              SizedBox(height: 10),
              if (canEdit)
                ElevatedButton.icon(
                  icon: Icon(Icons.people),
                  label: Text("Select Technician"),
                  onPressed: _openEmployeeSelector,
                ),
              SizedBox(height: 10),
              Wrap(
                spacing: 8,
                children: _employees
                    .where((e) => _selectedEmployeeIds.contains(e.id))
                    .map((employee) => Chip(
                          label: Text(employee.fullName ?? ''),
                          deleteIcon: canEdit ? Icon(Icons.close) : null,
                          onDeleted: canEdit
                              ? () => setState(() =>
                                  _selectedEmployeeIds.remove(employee.id))
                              : null,
                        ))
                    .toList(),
              ),
              SizedBox(height: 25),
            ],
            if (canEdit)
              ElevatedButton(
                onPressed: submit,
                child: Text(widget.workOrder == null
                    ? "Submit Report"
                    : "Save Changes"),
              ),
            if (widget.workOrder != null && canEdit) ...[
              SizedBox(height: 12),
              TextButton.icon(
                icon: Icon(Icons.delete_outline,
                    color: Colors.red, size: 18),
                label: Text("Delete work order",
                    style: TextStyle(color: Colors.red)),
                onPressed: _confirmDelete,
              ),
            ],
          ],
        ),
      ),
    );
  }

  Widget _buildActivityTab() {
    if (_commentsLoading) {
      return Center(
        child: CircularProgressIndicator(
            color: AppColors.accent, strokeWidth: 2),
      );
    }

    final hasContent = _comments.isNotEmpty || _attachments.isNotEmpty;

    if (!hasContent) {
      return Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Icon(Icons.chat_bubble_outline_rounded,
                size: 44, color: AppColors.bgSurface3),
            SizedBox(height: 12),
            Text('No activity yet',
                style: TextStyle(
                    fontSize: 14, color: AppColors.textTertiary)),
            SizedBox(height: 4),
            Text('Be the first to add a comment',
                style: TextStyle(
                    fontSize: 12, color: AppColors.textTertiary)),
          ],
        ),
      );
    }

    return RefreshIndicator(
      onRefresh: () async {
        setState(() => _refreshing = true);
        await _loadComments();
      },
      color: AppColors.accent,
      child: ListView.builder(
        controller: _activityScrollCtrl,
        physics: const AlwaysScrollableScrollPhysics(),
        keyboardDismissBehavior: ScrollViewKeyboardDismissBehavior.onDrag,
        padding: const EdgeInsets.fromLTRB(16, 14, 16, 16),
        itemCount: _comments.length + (_attachments.isNotEmpty ? 1 : 0),
        itemBuilder: (context, i) {
          if (_attachments.isNotEmpty && i == _comments.length) {
            return _AttachmentsSection(
              attachments: _attachments,
              onDelete: _deleteAttachment,
              currentUserEmail:
                  Supabase.instance.client.auth.currentUser?.email ?? '',
            );
          }
          final comment = _comments[i];
          final isLast = _attachments.isEmpty && i == _comments.length - 1;
          return _ActivityItem(
            comment: comment,
            isLast: isLast,
            currentUserEmail:
                Supabase.instance.client.auth.currentUser?.email ?? '',
          );
        },
      ),
    );
  }

  Widget _buildComposeBar() {
    final currentUser =
        Supabase.instance.client.auth.currentUser?.email ?? '';
    final initials = currentUser.split('@').first;
    final abbr = initials.length >= 2
        ? initials.substring(0, 2).toUpperCase()
        : initials.toUpperCase();

    return Container(
      color: AppColors.bgSurface,
      padding: const EdgeInsets.fromLTRB(12, 10, 12, 12),
      child: SafeArea(
        top: false,
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            if (_pendingAttachment != null)
              Padding(
                padding: const EdgeInsets.only(bottom: 8),
                child: PendingAttachmentChip(
                  file: _pendingAttachment!,
                  onRemove: _removePendingAttachment,
                ),
              ),
            Row(
              crossAxisAlignment: CrossAxisAlignment.end,
              children: [
                Container(
                  width: 36,
                  height: 36,
                  decoration: BoxDecoration(
                    color: AppColors.accentBg,
                    shape: BoxShape.circle,
                  ),
                  child: Center(
                    child: Text(abbr,
                        style: TextStyle(
                            fontSize: 12,
                            fontWeight: FontWeight.w500,
                            color: AppColors.accent)),
                  ),
                ),
                SizedBox(width: 10),
                Expanded(
                  child: Container(
                    clipBehavior: Clip.antiAlias,
                    decoration: BoxDecoration(
                      color: AppColors.bgSurface2,
                      borderRadius: BorderRadius.circular(20),
                      border:
                          Border.all(color: AppColors.border, width: 0.5),
                    ),
                    child: TextField(
                      controller: _commentCtrl,
                      maxLines: null,
                      keyboardType: TextInputType.multiline,
                      textInputAction: TextInputAction.newline,
                      style: TextStyle(
                          fontSize: 13, color: AppColors.textPrimary),
                      decoration: InputDecoration(
                        hintText: 'Add a comment…',
                        hintStyle: TextStyle(
                            fontSize: 13, color: AppColors.textTertiary),
                        filled: false,
                        border: InputBorder.none,
                        enabledBorder: InputBorder.none,
                        focusedBorder: InputBorder.none,
                        contentPadding:
                            EdgeInsets.symmetric(horizontal: 14, vertical: 9),
                      ),
                    ),
                  ),
                ),
                SizedBox(width: 6),
                GestureDetector(
                  onTap: _pickAttachment,
                  child: Container(
                    width: 36,
                    height: 36,
                    decoration: BoxDecoration(
                      color: AppColors.bgSurface2,
                      shape: BoxShape.circle,
                      border: Border.all(color: AppColors.border, width: 0.5),
                    ),
                    child: Icon(
                      Icons.attach_file,
                      size: 18,
                      color: AppColors.textSecondary,
                    ),
                  ),
                ),
                SizedBox(width: 6),
                GestureDetector(
                  onTap: _sending ? null : _sendComment,
                  child: Container(
                    width: 36,
                    height: 36,
                    decoration: BoxDecoration(
                      color: AppColors.accent,
                      shape: BoxShape.circle,
                    ),
                    child: _sending
                        ? Padding(
                            padding: EdgeInsets.all(10),
                            child: CircularProgressIndicator(
                                strokeWidth: 1.5, color: Colors.white),
                          )
                        : Icon(Icons.send_rounded,
                            size: 18, color: Colors.white),
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }

  Future<void> _confirmDelete() async {
    if (_isRequester) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Requester cannot delete work orders'),
          backgroundColor: AppColors.dangerText,
          behavior: SnackBarBehavior.floating,
        ),
      );
      return;
    }
    final confirm = await showDialog<bool>(
      context: context,
      builder: (context) => AlertDialog(
        title: Text("Delete Work Order"),
        content:
            Text("Are you sure you want to delete this work order?"),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context, false),
            child: Text("Cancel"),
          ),
          TextButton(
            onPressed: () => Navigator.pop(context, true),
            child: Text("Delete",
                style: TextStyle(color: Colors.red)),
          ),
        ],
      ),
    );
    if (confirm == true && widget.workOrder != null) {
      await _service.deleteWorkOrder(widget.workOrder!.id);
      if (!mounted) return;
      Navigator.pop(context, "deleted");
    }
  }

  void _openEmployeeSelector() {
    showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      builder: (context) => TechnicianSelector(
        technicians: _employees,
        selectedIds: _selectedEmployeeIds,
        onChanged: (ids) => setState(() => _selectedEmployeeIds = ids),
      ),
    );
  }
}

// ── Tab ───────────────────────────────────────────────────────────────────────

class _Tab extends StatelessWidget {
  final String label;
  final bool active;
  final int badge;
  final VoidCallback onTap;

  const _Tab({
    required this.label,
    required this.active,
    required this.onTap,
    this.badge = 0,
  });

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: onTap,
      child: Container(
        padding: const EdgeInsets.only(bottom: 10),
        margin: const EdgeInsets.only(right: 20),
        decoration: BoxDecoration(
          border: Border(
            bottom: BorderSide(
              color: active ? AppColors.accent : Colors.transparent,
              width: 2,
            ),
          ),
        ),
        child: Row(
          mainAxisSize: MainAxisSize.min,
          children: [
            Text(
              label,
              style: TextStyle(
                fontSize: 13,
                fontWeight: FontWeight.w500,
                color:
                    active ? AppColors.accent : AppColors.textSecondary,
              ),
            ),
            if (badge > 0) ...[
              SizedBox(width: 5),
              Container(
                padding:
                    const EdgeInsets.symmetric(horizontal: 5, vertical: 1),
                decoration: BoxDecoration(
                  color: active
                      ? AppColors.accent
                      : AppColors.bgSurface3,
                  borderRadius: BorderRadius.circular(8),
                ),
                child: Text(
                  '$badge',
                  style: TextStyle(
                    fontSize: 10,
                    fontWeight: FontWeight.w500,
                    color: active ? Colors.white : AppColors.textTertiary,
                  ),
                ),
              ),
            ],
          ],
        ),
      ),
    );
  }
}

// ── Status Pill ───────────────────────────────────────────────────────────────

class _StatusPill extends StatelessWidget {
  final String status;
  const _StatusPill({required this.status});

  @override
  Widget build(BuildContext context) {
    Color bg, fg;
    switch (status) {
      case 'In Progress':
        bg = AppColors.inProgressBg;
        fg = AppColors.inProgressText;
        break;
      case 'Closed':
        bg = AppColors.closedBg;
        fg = AppColors.closedText;
        break;
      default:
        bg = AppColors.pendingBg;
        fg = AppColors.pendingText;
    }
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
      decoration:
          BoxDecoration(color: bg, borderRadius: BorderRadius.circular(20)),
      child: Text(status,
          style: TextStyle(
              fontSize: 11, fontWeight: FontWeight.w500, color: fg)),
    );
  }
}

// ── Activity Item ─────────────────────────────────────────────────────────────

class _ActivityItem extends StatelessWidget {
  final WorkOrderComment comment;
  final bool isLast;
  final String currentUserEmail;

  const _ActivityItem({
    required this.comment,
    required this.isLast,
    required this.currentUserEmail,
  });

  Color get _avatarBg {
    if (comment.type == 'system') return AppColors.bgSurface2;
    final colors = [
      const Color(0xFFEEEDFE),
      const Color(0xFFE1F5EE),
      const Color(0xFFF5EBE6),
      const Color(0xFFE8F0FB),
    ];
    return colors[comment.authorName.hashCode.abs() % colors.length];
  }

  Color get _avatarFg {
    if (comment.type == 'system') return AppColors.textTertiary;
    final colors = [
      const Color(0xFF3C3489),
      const Color(0xFF085041),
      const Color(0xFF993C1D),
      const Color(0xFF0C447C),
    ];
    return colors[comment.authorName.hashCode.abs() % colors.length];
  }

  @override
  Widget build(BuildContext context) {
    return Row(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        // Left: avatar + connecting line
        SizedBox(
          width: 34,
          child: Column(
            children: [
              Container(
                width: 30,
                height: 30,
                decoration: BoxDecoration(
                  color: _avatarBg,
                  shape: BoxShape.circle,
                ),
                child: Center(
                  child: comment.type == 'system'
                      ? Icon(Icons.settings_outlined,
                          size: 14, color: AppColors.textTertiary)
                      : Text(comment.initials,
                          style: TextStyle(
                              fontSize: 11,
                              fontWeight: FontWeight.w500,
                              color: _avatarFg)),
                ),
              ),
              if (!isLast)
                Container(
                  width: 1,
                  height: 32,
                  margin: const EdgeInsets.symmetric(vertical: 4),
                  color: AppColors.border,
                ),
            ],
          ),
        ),
        SizedBox(width: 10),
        // Right: content
        Expanded(
          child: Padding(
            padding: EdgeInsets.only(bottom: isLast ? 0 : 6),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                // Meta row
                Row(
                  children: [
                    Text(
                      comment.authorEmail == currentUserEmail
                          ? 'You'
                          : comment.authorName,
                      style: TextStyle(
                          fontSize: 12,
                          fontWeight: FontWeight.w500,
                          color: AppColors.textPrimary),
                    ),
                    SizedBox(width: 6),
                    Text(comment.formattedTime,
                        style: TextStyle(
                            fontSize: 11,
                            color: AppColors.textSecondary)),
                    SizedBox(width: 6),
                    if (comment.type == 'comment')
                      Container(
                        padding: const EdgeInsets.symmetric(
                            horizontal: 5, vertical: 1),
                        decoration: BoxDecoration(
                          color: AppColors.accentBg,
                          borderRadius: BorderRadius.circular(6),
                        ),
                        child: Text('comment',
                            style: TextStyle(
                                fontSize: 10,
                                fontWeight: FontWeight.w500,
                                color: AppColors.accent)),
                      )
                    else if (comment.type == 'status_change')
                      Container(
                        padding: const EdgeInsets.symmetric(
                            horizontal: 5, vertical: 1),
                        decoration: BoxDecoration(
                          color: AppColors.inProgressBg,
                          borderRadius: BorderRadius.circular(6),
                        ),
                        child: Text('status',
                            style: TextStyle(
                                fontSize: 10,
                                fontWeight: FontWeight.w500,
                                color: AppColors.inProgressText)),
                      ),
                  ],
                ),
                SizedBox(height: 4),
                // Body
                if (comment.type == 'status_change' &&
                    comment.meta != null) ...[
                  Row(
                    children: [
                      _StatusBadge(
                          status: comment.meta!['from'] as String? ?? ''),
                      Padding(
                        padding: EdgeInsets.symmetric(horizontal: 6),
                        child: Icon(Icons.arrow_forward_rounded,
                            size: 12, color: AppColors.textTertiary),
                      ),
                      _StatusBadge(
                          status: comment.meta!['to'] as String? ?? ''),
                    ],
                  ),
                ] else
                  Text(
                    comment.body,
                    style: TextStyle(
                      fontSize: 13,
                      color: comment.type == 'system'
                          ? AppColors.textSecondary
                          : AppColors.textPrimary,
                      fontStyle: comment.type == 'system'
                          ? FontStyle.italic
                          : FontStyle.normal,
                      height: 1.5,
                    ),
                  ),
              ],
            ),
          ),
        ),
      ],
    );
  }
}

// ── Status Badge ──────────────────────────────────────────────────────────────

class _StatusBadge extends StatelessWidget {
  final String status;
  const _StatusBadge({required this.status});

  @override
  Widget build(BuildContext context) {
    Color bg, fg;
    switch (status) {
      case 'In Progress':
        bg = AppColors.inProgressBg;
        fg = AppColors.inProgressText;
        break;
      case 'Closed':
        bg = AppColors.closedBg;
        fg = AppColors.closedText;
        break;
      default:
        bg = AppColors.pendingBg;
        fg = AppColors.pendingText;
    }
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
      decoration:
          BoxDecoration(color: bg, borderRadius: BorderRadius.circular(8)),
      child: Text(status,
          style: TextStyle(
              fontSize: 11, fontWeight: FontWeight.w500, color: fg)),
    );
  }
}

// ── Attachments Section ───────────────────────────────────────────────────────

class _AttachmentsSection extends StatelessWidget {
  final List<WorkOrderAttachment> attachments;
  final Function(WorkOrderAttachment) onDelete;
  final String currentUserEmail;

  const _AttachmentsSection({
    required this.attachments,
    required this.onDelete,
    required this.currentUserEmail,
  });

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.only(top: 8, bottom: 4),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Container(
                width: 30,
                height: 30,
                decoration: BoxDecoration(
                  color: AppColors.accentBg,
                  shape: BoxShape.circle,
                ),
                child: Center(
                  child: Icon(
                    Icons.attach_file,
                    size: 14,
                    color: AppColors.accent,
                  ),
                ),
              ),
              SizedBox(width: 10),
              Container(
                width: 1,
                height: 32,
                color: AppColors.border,
              ),
              SizedBox(width: 10),
              Padding(
                padding: const EdgeInsets.only(bottom: 6),
                child: Text(
                  'Attachments (${attachments.length})',
                  style: TextStyle(
                    fontSize: 12,
                    fontWeight: FontWeight.w500,
                    color: AppColors.textSecondary,
                  ),
                ),
              ),
            ],
          ),
          Padding(
            padding: const EdgeInsets.only(left: 40),
            child: Wrap(
              spacing: 8,
              runSpacing: 8,
              children: attachments.map((attachment) {
                return SizedBox(
                  width: 200,
                  child: AttachmentWidget(
                    attachment: attachment,
                    showDelete: true,
                    onDelete: () => onDelete(attachment),
                  ),
                );
              }).toList(),
            ),
          ),
        ],
      ),
    );
  }
}
